# Generated by Django 5.1.1 on 2024-09-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0003_users_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinDev.resumes'),
        ),
    ]
