# Generated by Django 5.0.3 on 2024-09-14 19:51

import FinDev.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0007_users_resume_delete_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='reqs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(default='1', upload_to=FinDev.models.thumbnail_path),
            preserve_default=False,
        ),
    ]
