# Generated by Django 5.0.3 on 2024-09-14 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0008_posts_reqs_posts_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, related_name='applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='matched',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched', to=settings.AUTH_USER_MODEL),
        ),
    ]
