# Generated by Django 5.0.3 on 2024-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0010_users_profile_picture_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
