# Generated by Django 5.0.3 on 2024-09-15 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0011_chat_used'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chat',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='FinDev.posts'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('user1', 'user2', 'post')},
        ),
    ]
