# Generated by Django 5.0.3 on 2024-09-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0012_alter_chat_unique_together_chat_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
