# Generated by Django 5.0.3 on 2024-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0014_users_github_users_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role',
            new_name='devFocus',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='github',
            new_name='githubUsername',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='favoriteLanguage',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='John Doe', max_length=255),
            preserve_default=False,
        ),
    ]
