# Generated by Django 5.0.3 on 2024-09-15 06:59

import FinDev.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0015_rename_role_users_devfocus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=FinDev.models.pfp_path),
        ),
    ]
