# Generated by Django 5.0.3 on 2024-09-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0016_alter_users_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='role',
            new_name='devFocus',
        ),
    ]
