# Generated by Django 5.0.3 on 2024-09-15 07:47

import FinDev.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinDev', '0017_rename_role_posts_devfocus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=FinDev.models.resume_path),
        ),
    ]
